# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc1ea772b2ec4d2bf115e5c604097bc192c3ea76b9df306766ea9b4f599c1f3db1d19a2511160b750913e40c0b0d974990f412d1b364b6bb0fca12fba14cc47d

test:
  secret_key_base: 1b62e5e69a3a425d516a8081bef8d8c4cc31ccf816cbf5c2bc4e1e3337fbda1dd5e2e89e387d78f8b372b66fd7407a008a50f3fc152913063dccf5b118bc5f84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
